feat(poetry): exit early if curl is already installed

diff --git a/poetry/orb.yaml b/poetry/orb.yaml
--- a/poetry/orb.yaml
+++ b/poetry/orb.yaml
@@ -26,24 +26,24 @@ commands:
         type: string
     steps:
       - run:
-          name: Install curl
+          name: install curl
           command: |
+            if [ -n "$(command -v curl)" ]; then
+              return
+            fi
             if cat /etc/issue | grep "Alpine" >/dev/null 2>&1; then
               if [ "$ID" = 0 ]; then export SUDO=""; else export SUDO="sudo"; fi
             else
               if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
             fi
-            echo "export SUDO=$SUDO" >> ${BASH_ENV}
-            if [ ! "$(command -v curl)" ]; then
-              if which apk >/dev/null; then
-                $SUDO apk add --no-cache --no-progress curl
-              elif which apt-get >/dev/null; then
-                $SUDO apt-get update -qy
-                $SUDO apt-get install -qy curl
-              else
-                echo >&2 "ERROR: could not find supported package manager"
-                exit 1
-              fi
+            if which apk >/dev/null; then
+              $SUDO apk add --no-cache --no-progress curl
+            elif which apt-get >/dev/null; then
+              $SUDO apt-get update -qy
+              $SUDO apt-get install -qy curl
+            else
+              echo >&2 "ERROR: could not find supported package manager"
+              exit 1
             fi
       - unless:
           condition:
